# Generated by Django 5.2.5 on 2025-08-24 16:45

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=500, null=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("office", "Office"),
                            ("life", "Life"),
                            ("fundraise", "Fundraise"),
                            ("others", "Others"),
                        ],
                        default="others",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("success", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Fundraise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "raised_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("UGX", "Ugandan Shillings"), ("USD", "US Dollars")],
                        default="UGX",
                        max_length=3,
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundraise",
                        to="article.article",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
