# Generated by Django 5.2.5 on 2025-08-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="location",
            field=models.CharField(blank=True, null=True),
        ),
    ]
