# Generated by Django 5.2.5 on 2025-08-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_article_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.CharField(default="help", max_length=255),
        ),
    ]
