# Generated by Django 5.2.5 on 2025-08-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_article_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_fundraise",
            field=models.BooleanField(default=False),
        ),
    ]
