# Generated by Django 5.2.5 on 2025-08-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_article_is_fundraise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.CharField(default="list", max_length=50),
        ),
    ]
